server:
  port: 8080
# spring doc
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

# aws-cloud
cloud:
  aws:
    credentials:
      accessKey: AKIA5EK2XZJUKDDHOFPV       # AWS IAM AccessKey 적기
      secretKey: gXNi+uzOvH0OOlMNQ/XXjsibxsSnxVxMaeU0zhpT  # AWS IAM SecretKey 적기
    s3:
      bucket: kdt9hotdog    # ex) marryting-gyunny
      dir: profileImage # ex) /gyunny

    region:
      static: ap-northeast-2
    stack:
      auto: false