server:
  port: 8080
# spring doc
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

# aws-cloud
cloud:
  aws:
    credentials:
      accessKey: AKIA6GQIYR7AT3DGOSF6       # AWS IAM AccessKey 적기
      secretKey: pAuc/Uw/0u4fj0Mu8Rc0NwMJJNWwGW1L8IImyFm2   # AWS IAM SecretKey 적기
    s3:
      bucket: kdt9-justin    # ex) marryting-gyunny
      dir: kdt9-justin # ex) /gyunny
    region:
      static: ap-northeast-2
    stack:
      auto: false