springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true